### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ralphtheninja** [MrChrisJ/World-Citizenship#6]
I think it would be wise to add a license to the project. I don't really have an opinion on which license to use (I mainly use MIT myself) as long as it has one. This is just to be clear for what can be done with the content in case you fork it etc.

**Comment by happygiraffee** [comment]
as a new-bee I am a bit disappointed that CC0 is out of favour here...

**Comment by happygiraffee** [comment]
as a new-bee I am a bit disappointed that CC0 is out of favour here...

**Comment by ryepdx** [comment]
From my perspective, requiring sharing is a protective measure to prevent our work from being co-opted by private interests. It seems to me the most pragmatic option given our goals here. But what in particular appeals to you about CC0 versus something like CC-SA-BY?

**Comment by MrChrisJ** [comment]
One argument in favour of @happygiraffee is that it could prevent business opportunities emerging if entrepreneurs felt restricted by SA-BY. I am willing to be persuaded on this issue if a good argument is presented because in real terms I think we all know that there are no enforcement agents when it comes to these kind of licences so really all we are doing is declaring our intent.

**Comment by thecuriosity** [comment]
I think CC-SA-BY will discourage contribution by firms, and in a way reduce the popularity of the project.

**Comment by happygiraffee** [comment]
Echoing with @MrChrisJ and @thecuriosity I consider the potential for business opportunity and project popularity as among the advantages of CC0, but what particularly appeals to me is also the liberty that it grants its users.

**Comment by apotheon** [comment]
I, for one, am rather disappointed with the use of a restrictive license for this project -- and any license with compatibility issues like almost the entire set of CC licenses (CC0 is the only one without any meaningful compatibility issues) is restrictive in some very practical ways, damaging for the ability to reuse in conjunction with other "open" licenses.  In general, I consider CC licenses other than CC0 to basically be no-derivatives licenses because of the legal prohibitions arising as emergent properties of the incompatibility with other licenses.

. . . and, frankly, you can't stop a government from using something by applying copyright law when the government makes the law.  Just a few years ago (for example), US Congress actually declared some classical music compositions whose copyrights had expired, leaving those compositions in the public domain for decades, under copyright once more to match the law in the country of origin for those compositions as an exception to the otherwise generally consistent law on the matter.

Trying to use the law to stop the entity that *defines* the law from using your software is an exercise in futility, in the end.  Just use whatever means the law provides to nullify the restrictions placed by that law, by default, on what you want to share so those of us who want to combine good things to make even better things won't fear having our lives destroyed in court for expanding the reach and advancement of human learning.

To maximize reusability and legal access, the term for the class of licensing I'd recommend is [copyfree](http://copyfree.org/standard/).  Given the application of CC-anything-other-than-zero, the most I'd do with this project is learn from it, then find ways to disseminate the lessons learned to others in a way they wouldn't be discouraged from using without running afoul of your copyright privileges.

**Comment by wrapperband** [comment]
Thanks for that copyright information, apotheon. You convinced me...

**Comment by MrChrisJ** [comment]
Hey @apotheon well put thanks for taking the time to share your thoughts.. @wrapperband I am convinced too. I have updated it to CC0 for now to bring it in to line with the Fullnode project https://github.com/MrChrisJ/World-Citizenship/commit/273eb43210b8e4320edc7b1b9a45b8cc5c12cf40

**Comment by apotheon** [comment]
Wow . . . thanks for taking my commentary well.  I appreciate that, and will try to find time within my job's 20% Time hours allotment to find ways to contribute to this CC0 project.
